### ISSUE TITLE
Cannot read property 'spec' of undefined

### ISSUE THREAD

**Issue by jftanner** [IBM/tekton-lint#1] opened 2020-10-05 19:55 UTC
First off, congratulations on your open source release! That's momentous!

Now, on to the error. Linting my pipeline results in the following:
```
TypeError: Cannot read property 'spec' of undefined
    at /mnt/c/Users/JAMESTANNER/Development/microservices-build-agent/node_modules/tekton-lint/rules/no-undefined-result.js:14:83
```

I _think_ that this happens because I've got an external task which is loaded separately from the catalog. So it's not included in the files being linted. So there's a taskref in the pipeline, but no task to match against.

I'd expect the behavior here to be a warning, or perhaps a displayed error, about the missing task. But I'd expect the linter to _complete_ rather than throwing an internal error.

If you have access to the IBM internal github, the pipeline in question is here: https://github.ibm.com/TAAS/microservices-builds/blob/main/tekton-pipeline/pipeline-push.yaml
From some extra logging I injected into the code, it looks like it fails on the `fetch-from-git` task.

**Comment by madbence** [comment] 2020-10-05 23:25
You're right, the issue is that the linter is trying to look up the task based on `taskRef`, and it can't find it among the loaded definitions.

I think the appropriate behavior here would be to report a warning, as it cannot really check whether `git-commit` is something that `git-clone-repo` emits.

**Comment by madbence** [comment] 2020-10-06 20:27
@jftanner I checked the definition you mentioned with `0.4.2`, and it no longer crashes! It'll report _errors_, as that's the current default behavior for missing tasks, but that can be fixed by adding the tasks to the definitions (the linter accepts multiple globs, ie. you can do `tekton-lint path/to/definitions/*.yaml ../something/totally/different/*.yaml`), or turning off that rule (this feature is not documented yet).

**Closed by madbence** 2020-10-06 20:27 UTC
Labels: good first issue

**Comment by jftanner** [comment] 2020-10-06 20:42
@madbence That's awesome! I'll upgrade and check it out.

The task in question is from the catalogue. (Specifically, [here](https://github.com/open-toolchain/tekton-catalog/tree/master/git).)
Is there any plans to support remotely-sourced definitions like this, or would I need to download copies for linting?

**Comment by madbence** [comment] 2020-10-06 21:57
I think the linter _could_ support resolving URLs, but that opens up a bunch of other questions... Eg. you won't be able to import `https://example.com/tasks/*.yaml`, how can you specify headers for these requests?

For now, I'd recommend actually cloning those definitions
